Repository AY2324S2-CS2103-F09-1/tp, pull requests merged in 2024-03, with the labels that each got.

#34 Update EstateEase Developer Guide
  docs/DeveloperGuide.md
Labels: US6, US10, US14, US15

#33 Add 3 UCs for US11, US12, US19
  docs/DeveloperGuide.md
Labels: US11, US12, US19

#36 Update developer guide's user story table, use case sequences, and add use cases for us5, us13, us18.
  docs/DeveloperGuide.md
Labels: US5, US13, US18

#55 Add Postal Code
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/PostalCode.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/house/PostalCodeTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#56 Add Block Class
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/Block.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/house/BlockTest.java
Labels: enhancement

#59 Add Unit Number
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/UnitNumber.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/house/UnitNumberTest.java
Labels: enhancement

#58 Add Level class
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/Level.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/house/LevelTest.java
Labels: enhancement

#57 Add Street Class
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/Street.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/house/StreetTest.java
Labels: enhancement

#60 Create Seller and Buyer classes with add commands and test cases
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Seller.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
Labels: enhancement

#64 Branch-Add-Seller
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/model/house/Landed.java
  src/main/java/seedu/address/model/house/NonLanded.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedHouseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
  src/test/java/seedu/address/testutil/TypicalHouses.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: US1

#65 Merge Branch-Add-Seller
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/model/house/Landed.java
  src/main/java/seedu/address/model/house/NonLanded.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedHouseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
  src/test/java/seedu/address/testutil/TypicalHouses.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#70 PUML Diagram Update
  docs/diagrams/ModelClassDiagram.puml
Labels: enhancement

#71 Add Class Level, UnitNumber, and link PostalCode and Street to Seller
  docs/diagrams/ModelClassDiagram.puml
Labels: enhancement

#74 Update UML diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#75 Update PUML
  docs/diagrams/ModelClassDiagram.puml
Labels: enhancement

#79 Add Budget class for Buyer class
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Budget.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/BuyerBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#80 Add edit buyer command and its test cases
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditBuyerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditBuyerCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditBuyerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#85 Add author tag
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#86 Update Developer Guide for Matching Buyer Feature
  docs/DeveloperGuide.md
Labels: enhancement

#88 Update DG to include add seller command
  docs/DeveloperGuide.md
Labels: documentation

#90 Update implementation for add buyer feature
  docs/DeveloperGuide.md
Labels: documentation

#92 Update App Version and Enable Assertions
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: enhancement

#89 Update Developer Guide and Minor Update UML Diagram
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: documentation

#93 Add HousingType Class
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/HousingType.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/testutil/BuyerBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
Labels: enhancement

#95 Branch Update Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSellerActivityDiagram.puml
  docs/diagrams/AddSellerSequenceDiagram-Logic.puml
  docs/diagrams/AddSellerSequenceDiagram-Model.puml
  docs/diagrams/AddSellerSequenceDiagram-Storage.puml
Labels: documentation

#98 Merge branch-edit-buyer-command to master
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditBuyerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditBuyerCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditBuyerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#100 Add Price class to HDB class, Condominium class, Landed class
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/Condominium.java
  src/main/java/seedu/address/model/house/Hdb.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/model/house/Landed.java
  src/main/java/seedu/address/model/house/Price.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/storage/JsonAdaptedHouseTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/testutil/TypicalHouses.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement
