Repository AY2324S2-CS2103-F09-1/tp, pull requests merged in 2024-04, with the labels that each got.

#103 Branch Add/Update Json
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/model/house/HousingType.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/testutil/BuyerBuilder.java
  src/test/java/seedu/address/testutil/EditBuyerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#101 Add Addhouse Command
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/parser/AddHouseCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/model/house/UniqueHouseList.java
  src/main/java/seedu/address/model/house/exceptions/DuplicateHouseException.java
  src/main/java/seedu/address/model/house/exceptions/HouseNotFoundException.java
  src/main/java/seedu/address/model/house/exceptions/MissingHouseException.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/InvalidSellerException.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: enhancement

#106 Bug fix for add house
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/parser/AddHouseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/house/exceptions/DuplicateHouseException.java
  src/main/java/seedu/address/model/house/exceptions/HouseNotFoundException.java
  src/main/java/seedu/address/model/house/exceptions/MissingHouseException.java
  src/main/java/seedu/address/model/person/exceptions/InvalidSellerException.java
Labels: bug

#104 Add edit seller command
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSellerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditSellerCommandParserTest.java
  src/test/java/seedu/address/testutil/EditSellerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#112 Revert "Branch add json test case 1"
  src/main/java/seedu/address/logic/Messages.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddSellerCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/house/HousingTypeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
Labels: invalid

#109 Add buyer seller tags according to person type
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditBuyerDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSellerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditSellerCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/BuyerBuilder.java
  src/test/java/seedu/address/testutil/EditBuyerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditSellerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation

#120 Update SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: enhancement

#119 Add match Buyer Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MatchBuyerCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/house/Condominium.java
  src/main/java/seedu/address/model/house/Hdb.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/model/house/Landed.java
  src/main/java/seedu/address/model/house/Price.java
  src/main/java/seedu/address/model/house/PriceAndHousingTypePredicate.java
  src/main/java/seedu/address/model/person/Budget.java
  src/main/java/seedu/address/model/person/FullNameEqualsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Seller.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: enhancement

#121 Add sorting function to internal list
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: enhancement

#123 Branch-Code-Quality
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddHouseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: enhancement

#122 Update DG to include match buyer implementation with sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/MatchBuyerSequenceDiagram-Logic.puml
Labels: documentation

#124 Update developer guide
  docs/DeveloperGuide.md
Labels: documentation

#125 Implement view person command for seller's logic
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/ui/HouseCard.java
  src/main/java/seedu/address/ui/HouseListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/resources/view/HouseListCard.fxml
  src/main/resources/view/HouseListPanel.fxml
  src/main/resources/view/PersonDetailsPanel.fxml
  src/test/java/seedu/address/model/person/SellerTest.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
Labels: US12

#126 Branch Code Enhancement
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/house/House.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/test/java/seedu/address/logic/parser/EditBuyerCommandParserTest.java
Labels: enhancement

#127 Add PUML diagram, User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddHouseSequenceDiagram-Logic.puml
  docs/diagrams/AddSellerActivityDiagram.puml
  docs/diagrams/DeleteHouseSequenceDiagram-Logic.puml
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/house/UniqueHouseList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/BuyerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/SellerTest.java
Labels: documentation

#130 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddSellerActivityDiagram.puml
  docs/diagrams/AddSellerSequenceDiagram-Logic.puml
  docs/diagrams/AddSellerSequenceDiagram-Storage.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation

#129 Display match result from match buyer command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MatchResultCard.java
  src/main/java/seedu/address/ui/MatchResultListPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CustomisedTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MatchResultListCard.fxml
  src/main/resources/view/MatchResultListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: enhancement

#131 Update documentation
  docs/DeveloperGuide.md
  docs/diagrams/EditBuyerSequenceDiagram.puml
Labels: documentation

#134 Update User Guide to include matchBuyer feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
Labels: documentation

#135 Update Developer Guide and User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSellerSequenceDiagram-Logic.puml
  src/main/java/seedu/address/model/house/UniqueHouseList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: documentation

#138 Update ui design for the app
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHouseCommand.java
  src/main/java/seedu/address/ui/HouseCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/budget_icon.png
  src/main/resources/images/email_icon.png
  src/main/resources/images/house_icon.png
  src/main/resources/images/phone_icon.png
  src/main/resources/images/real_estate_icon.png
  src/main/resources/images/real_estate_icon2.png
  src/main/resources/view/CustomisedTheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HouseListCard.fxml
  src/main/resources/view/HouseListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MatchResultListCard.fxml
  src/main/resources/view/MatchResultListPanel.fxml
  src/main/resources/view/PersonDetailsPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: enhancement

#139 Add viewCommand sequence diagram in DG
  docs/diagrams/ViewSequenceDiagram-Logic.puml
Labels: documentation

#136 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/EditBuyerSequenceDiagram.puml
  docs/images/ui-screenshots/addSeller-success.png
  docs/images/ui-screenshots/editBuyer-success.png
  docs/images/ui-screenshots/editSeller-success.png
  docs/images/ui-screenshots/list-success.png
  docs/images/ui-screenshots/matchBuyer-success.png
  docs/images/ui-screenshots/view-success.png
  docs/img.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#144 Branch add user guide 7
  docs/UserGuide.md
  src/main/resources/view/CustomisedTheme.css
Labels: documentation

#143 Update developer guide for matchBuyer acitivity diagram
  docs/DeveloperGuide.md
  docs/diagrams/MatchBuyerActivityDiagram.puml
Labels: documentation

#148 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#146 Update user guide
  docs/diagrams/AddHouseSequenceDiagram-Logic.puml
  docs/diagrams/DeleteHouseSequenceDiagram-Logic.puml
Labels: documentation

#145 Branch update documentation
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/images/ui-screenshots/find-success.png
  docs/images/ui-screenshots/helpMessage.png
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#204 Fix bug of address not displaying correctly when a landed house is added
  src/main/java/seedu/address/ui/HouseCard.java
  src/main/resources/view/HouseListCard.fxml
Labels: bug

#208 Fix typo in addBuyer command in UG
  docs/UserGuide.md
Labels: documentation bug

#202 Update user guide to clarify the matching process and fix the bug of incorrect data displayed for matchBuyer
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: documentation

#205 Add enhanced implementation appendix to propose matchSeller Command and 1 trillion limit to price and budget
  docs/DeveloperGuide.md
Labels: documentation

#201 Fix documentation bug
  docs/UserGuide.md
Labels: documentation

#207 Branch Debug 2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#212 Update User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation bug

#211 Update dg and ug to address 2d.p. problem
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/house/Price.java
  src/main/java/seedu/address/model/person/Budget.java
Labels: documentation

#213 Update code quality
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHouseCommand.java
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
Labels: code quality

#210 Fix issue of displaying N/A in house
  src/main/java/seedu/address/ui/HouseCard.java
Labels: bug

#214 Branch code quality
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddHouseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteHouseCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
  src/main/java/seedu/address/logic/parser/AddHouseCommandParser.java
  src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/house/Condominium.java
  src/main/java/seedu/address/model/house/Hdb.java
  src/main/java/seedu/address/model/house/Landed.java
  src/main/java/seedu/address/model/house/PriceAndHousingTypePredicate.java
  src/main/java/seedu/address/model/house/UniqueHouseList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedHouse.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/HouseCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MatchResultListPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailsPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/Ui.java
Labels: code quality

#215 Branch Update Code Quality and Fix Functionality Bug
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/house/UnitNumber.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/house/UnitNumberTest.java
Labels: functionality bug, code quality

#216 Update Code quality in UG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/team/johndoe.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/house/PostalCode.java
  src/main/java/seedu/address/model/house/UnitNumber.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Budget.java
  src/main/java/seedu/address/model/person/Buyer.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Seller.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/HouseCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSellerCommandTest.java
Labels: documentation

#217 Update UG
  docs/UserGuide.md
Labels: documentation

#218 Update UserGuide
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#219 Branch Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSellerSequenceDiagram-Logic.puml
Labels: documentation

#220 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddBuyerActivityDiagram.puml
  docs/diagrams/AddHouseSequenceDiagram-Logic.puml
  docs/site.json
Labels: documentation

#221 Update website icon
  docs/images/real_estate_icon.png
Labels: documentation

#222 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#224 Update the app icon to a square resolution
  docs/images/real_estate_icon.png
Labels: documentation

#226 Update the app icon to a square resolution
  docs/images/real_estate_icon.png
Labels: documentation

#223 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#225 Update Documentation
  docs/DeveloperGuide.md
Labels: documentation

#227 Update Developers Guide
  docs/DeveloperGuide.md
Labels: documentation

#228 Update Documentation
  docs/DeveloperGuide.md
Labels: documentation

#229 Add manual testing for Add a Buyer
  docs/DeveloperGuide.md
Labels: documentation

#230 Refactor Ui screenshot filename
  README.md
  build.gradle
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/estate_ease_ui.png
  docs/index.md
Labels: enhancement

#231 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#234 Fix incorrect UI display in MatchBuyerCommand
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
Labels: ui bug

#233 Add an enhancement to the proposed enhancement
  docs/DeveloperGuide.md
Labels: documentation

#232 Update Enhanced Implementation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#235 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#236 Update model and ui class diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: documentation

#237 Update dg
  docs/DeveloperGuide.md
Labels: documentation

#238 Add credits for the parts that I reused code from some inspiration
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: documentation

#241 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/AddBuyerSequenceDiagram-Logic.puml
  docs/diagrams/AddHouseSequenceDiagram-Logic.puml
  docs/diagrams/AddSellerSequenceDiagram-Logic.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteHouseSequenceDiagram-Logic.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/MatchBuyerSequenceDiagram-Logic.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram-Logic.puml
Labels: documentation

#240 Refactor boolean variables to follow java convention
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/HouseListPanel.java
  src/main/java/seedu/address/ui/MatchResultListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: code quality

#239 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#244 Fix incorrect UI display in MatchBuyerCommand
  src/main/java/seedu/address/logic/commands/MatchBuyerCommand.java
Labels: documentation

#243 Update formatting issues in UG
  docs/DeveloperGuide.md
Labels: documentation

#245 Add a page break
  docs/DeveloperGuide.md
Labels: documentation

#246 Add proposed enhancement for index integer overflow
  docs/DeveloperGuide.md
Labels: documentation

#247 Change width of some uml diagram
  docs/DeveloperGuide.md
Labels: documentation
